# espanso match file: https://espanso.org/docs/matches/basics/

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Check espanso is running
  - trigger: ":espanso"
    replace: "Hi there!"

  # Utilities

  # Print the current date
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Print the output of a shell command
  # - trigger: ":shell"
  #   replace: "{{output}}"
  #   vars:
  #     - name: output
  #       type: shell
  #       params:
  #         cmd: "echo 'Hello from your shell'"

  # Symbols
  - trigger: :euro
    replace: "\u20ac"
  - trigger: :pound
    replace: "\u00a3"

  # Typo correction
  - trigger: "ther"
    replace: "there"
    propagate_case: true
    word: true
  - trigger: "strenght"
    replace: "strength"
    propagate_case: true
    word: true
  - trigger: "tho"
    replace: "though"
    propagate_case: true
    word: true
  - trigger: "thru"
    replace: "through"
    propagate_case: true
    word: true
