name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker
        run: |
          docker --version
      
      - name: Run tests
        run: |
          sh scripts/tests.sh
      
      - name: Upload test report to summary
        if: always()
        run: |
          if [ -f test_report.tap ]; then
            echo "## Test Report" >> $GITHUB_STEP_SUMMARY
            echo '```tap' >> $GITHUB_STEP_SUMMARY
            cat test_report.tap >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
